// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteConfig = XP.SiteConfig;

declare global {
  namespace XP {
    interface SiteConfig {
      /**
       * Name
       */
      name?: string;

      /**
       * Short Name
       */
      short_name?: string;

      /**
       * Background color
       */
      background_color?: string;

      /**
       * Theme color
       */
      theme_color?: string;

      /**
       * Description
       */
      description?: string;

      /**
       * Display
       */
      display?: "fullscreen" | "standalone" | "minimal-ui" | "browser";

      /**
       * Categories
       */
      categories?: Array<"beauty" | "books" | "books & reference" | "business" | "cars" | "dating" | "design" | "developer" | "developer tools" | "development" | "education" | "entertainment" | "events" | "fashion" | "finance" | "fitness" | "food" | "fundraising" | "games" | "government" | "graphics" | "graphics & design" | "health" | "health & fitness" | "kids" | "lifestyle" | "magazines" | "medical" | "multimedia" | "multimedia design" | "music" | "navigation" | "network" | "networking" | "news" | "parenting" | "personalization" | "pets" | "photo" | "photo & video" | "politics" | "productivity" | "reference" | "security" | "shopping" | "social" | "social networking" | "sports" | "transportation" | "travel" | "utilities" | "video" | "weather"> | "beauty" | "books" | "books & reference" | "business" | "cars" | "dating" | "design" | "developer" | "developer tools" | "development" | "education" | "entertainment" | "events" | "fashion" | "finance" | "fitness" | "food" | "fundraising" | "games" | "government" | "graphics" | "graphics & design" | "health" | "health & fitness" | "kids" | "lifestyle" | "magazines" | "medical" | "multimedia" | "multimedia design" | "music" | "navigation" | "network" | "networking" | "news" | "parenting" | "personalization" | "pets" | "photo" | "photo & video" | "politics" | "productivity" | "reference" | "security" | "shopping" | "social" | "social networking" | "sports" | "transportation" | "travel" | "utilities" | "video" | "weather";

      /**
       * Icon
       */
      iconId?: string;

      /**
       * Shortcuts
       */
      shortcuts?: Array<{
        /**
         * Name
         */
        name: string;

        /**
         * Short Name
         */
        short_name?: string;

        /**
         * Description
         */
        description?: string;

        /**
         * URL
         */
        pageId: string;

        /**
         * Icon
         */
        iconId?: string;
      }>;

      /**
       * Related applications
       */
      related_applications?: Array<{
        /**
         * Platform
         */
        platform: "chrome_web_store" | "play" | "chromeos_play" | "webapp" | "windows" | "f-droid" | "amazon";

        /**
         * URL
         */
        url?: string;
      }>;

      /**
       * Screenshots
       */
      screenshots?: Array<{
        /**
         * Image
         */
        imageId: string;

        /**
         * Form factor
         */
        form_factor: "narrow" | "wide";
      }>;
    }
  }
}
